service: devops-csv

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  lambdaHashingVersion: '20201221'
  stackName: devops-csv
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AdministratorAccess

package:
  individually: true

functions:
  test:
    name: devops-csv
    description: Lambda for inserting csv file into dynamodb
    handler: handler.handler
    memorySize: 256        
    timeout: 600
    events:
      - s3:
          bucket: bucket-csv
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
          existing: true

resources:
  Resources:
    CourseTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: employees
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        Tags:
          - Key: Name
            Value: employees
